### PR TITLE
Avoid installation of GTest

### PR DESCRIPTION
**Pull request by CongMa13**
GTest should not be installed with RocWmma lib

### CODE REVIEW

**Comment by CongMa13** [comment]
GTest will not be installed with RocWmma.

install_manifest

> /opt/rocm/include/rocwmma/internal/blend.hpp
/opt/rocm/include/rocwmma/internal/blend_impl.hpp
/opt/rocm/include/rocwmma/internal/broadcast.hpp
/opt/rocm/include/rocwmma/internal/dpp.hpp
/opt/rocm/include/rocwmma/internal/constants.hpp
/opt/rocm/include/rocwmma/internal/convert.hpp
/opt/rocm/include/rocwmma/internal/mfma.hpp
/opt/rocm/include/rocwmma/internal/wmma.hpp
/opt/rocm/include/rocwmma/internal/wmma_impl.hpp
/opt/rocm/include/rocwmma/internal/coop_load.hpp
/opt/rocm/include/rocwmma/internal/coop_store.hpp
/opt/rocm/include/rocwmma/internal/flow_control.hpp
/opt/rocm/include/rocwmma/internal/layout_impl.hpp
/opt/rocm/include/rocwmma/internal/opaque_load.hpp
/opt/rocm/include/rocwmma/internal/io_traits.hpp
/opt/rocm/include/rocwmma/internal/opaque_store.hpp
/opt/rocm/include/rocwmma/internal/config.hpp
/opt/rocm/include/rocwmma/internal/mapping_util.hpp
/opt/rocm/include/rocwmma/internal/mapping_util_impl.hpp
/opt/rocm/include/rocwmma/internal/vector.hpp
/opt/rocm/include/rocwmma/internal/float8.h
/opt/rocm/include/rocwmma/internal/mfma_impl.hpp
/opt/rocm/include/rocwmma/internal/pack_util_impl.hpp
/opt/rocm/include/rocwmma/internal/pack_util.hpp
/opt/rocm/include/rocwmma/internal/type_traits.hpp
/opt/rocm/include/rocwmma/internal/permute.hpp
/opt/rocm/include/rocwmma/internal/types.hpp
/opt/rocm/include/rocwmma/internal/utils.hpp
/opt/rocm/include/rocwmma/internal/vector_impl.hpp
/opt/rocm/include/rocwmma/internal/transforms.hpp
/opt/rocm/include/rocwmma/internal/transforms_impl.hpp
/opt/rocm/include/rocwmma/internal/rocwmma_hip_f8_impl.h
/opt/rocm/include/rocwmma/internal/rocwmma_xfloat32.hpp
/opt/rocm/include/rocwmma/internal/types_ext.hpp
/opt/rocm/include/rocwmma/internal/types_impl.hpp
/opt/rocm/include/rocwmma/internal/vector_iterator.hpp
/opt/rocm/include/rocwmma/internal/cross_lane_ops.hpp
/opt/rocm/include/rocwmma/internal/dpp_impl.hpp
/opt/rocm/include/rocwmma/internal/io_config.hpp
/opt/rocm/include/rocwmma/internal/io_shape.hpp
/opt/rocm/include/rocwmma/internal/layout.hpp
/opt/rocm/include/rocwmma/internal/permute_impl.hpp
/opt/rocm/include/rocwmma/internal/swizzle.hpp
/opt/rocm/include/rocwmma/internal/swizzle_impl.hpp
/opt/rocm/include/rocwmma/rocwmma.hpp
/opt/rocm/include/rocwmma/rocwmma_coop_impl.hpp
/opt/rocm/include/rocwmma/rocwmma_transforms.hpp
/opt/rocm/include/rocwmma/rocwmma_transforms_impl.hpp
/opt/rocm/include/rocwmma/rocwmma-version.hpp
/opt/rocm/include/rocwmma/rocwmma_coop.hpp
/opt/rocm/include/rocwmma/rocwmma_impl.hpp
/opt/rocm/share/doc/rocwmma/LICENSE.md
/opt/rocm/bin/simple_sgemm
/opt/rocm/bin/perf_sgemm
/opt/rocm/bin/simple_hgemm
/opt/rocm/bin/perf_hgemm
/opt/rocm/bin/simple_dgemm
/opt/rocm/bin/perf_dgemm
/opt/rocm/bin/simple_sgemv
/opt/rocm/bin/simple_dgemv
/opt/rocm/bin/simple_dlrm
/opt/rocm/bin/hipRTC_gemm
/opt/rocm/bin/rocwmma/CTestTestfile.cmake
/opt/rocm/bin/gemm_PGR1_LB2_MP0_MB_CP_ad_hoc-validate
/opt/rocm/bin/gemm_PGR1_LB2_MP0_MB_CP_BLK-validate
/opt/rocm/bin/gemm_PGR1_LB2_MP0_MB_CP_WV-validate
/opt/rocm/bin/gemm_PGR1_LB2_MP0_MB_CP_WG-validate
/opt/rocm/bin/gemm_PGR0_LB0_MP0_SB_NC-validate
/opt/rocm/bin/gemm_PGR0_LB0_MP0_SB_NC_ad_hoc-validate
/opt/rocm/bin/gemm_PGR0_LB0_MP0_MB_NC-validate
/opt/rocm/bin/gemm_PGR0_LB0_MP0_MB_NC_ad_hoc-validate
/opt/rocm/bin/contamination_test
/opt/rocm/bin/layout_test
/opt/rocm/bin/map_util_test
/opt/rocm/bin/load_store_matrix_sync_test
/opt/rocm/bin/load_store_matrix_coop_sync_test
/opt/rocm/bin/fill_fragment_test
/opt/rocm/bin/vector_iterator_test
/opt/rocm/bin/vector_test
/opt/rocm/bin/io_traits_test
/opt/rocm/bin/cross_lane_ops_test
/opt/rocm/bin/io_shape_test
/opt/rocm/bin/dlrm_dot_test-validate
/opt/rocm/bin/dlrm_dot_lds_test-validate

**Review by dlangbe — APPROVED** [review]
LGTM!

**Review by cgmillette — APPROVED** [review]
Looks good! Can you please duplicate this PR against release-staging/rocm-rel-6.0 ?

**Comment by CongMa13** [comment]
> Looks good! Can you please duplicate this PR against release-staging/rocm-rel-6.0 ?

Sure. Created PR #257 against release-staging/rocm-rel-6.0, which is a duplicate of this PR.

**Pull request merged**
