### PR TITLE
Update dependabot.yml config

### PR DESCRIPTION
**Pull request by samjwu**
Update dependabot.yml directory config to point to documentation dependencies only

### CODE REVIEW

**Review by cgmillette — APPROVED** [review]

**Comment by cgmillette** [comment]
@samjwu does this need to be cherry picked for ROCm 5.6 release?

**Comment by samjwu** [comment]
> @samjwu does this need to be cherry picked for ROCm 5.6 release?

I believe so, though maybe @saadrahim can confirm.

The documentation theme in rocm-docs-core is planned to have updates to meet with compliance guidelines, which dependabot will make PRs for to update each repository.

**Review by mkarunan — APPROVED** [review]
Looks good

**Comment by saadrahim** [comment]
This should go in the release branch as well as the dependabot changes that are triggered.

**Comment by cgmillette** [comment]
> This should go in the release branch as well as the dependabot changes that are triggered.

@mkarunan can you please ensure @saadrahim 's request? Thanks

**Comment by mkarunan** [comment]
Yes Chris, once all the changes are merged, will cherrypick a PR into the release-staging branch

**Pull request merged**
