### PR TITLE
Add script to dump benchmark outputs

### PR DESCRIPTION
**Pull request by mkarunan**

### CODE REVIEW

**Review by cgmillette — COMMENTED** [review]
For gemm_PGR1_LB2_MP0_MB_CP,
you will get 3 variants:
gemm_PGR1_LB2_MP0_MB_CP_BLK
gemm_PGR1_LB2_MP0_MB_CP_WV
gemm_PGR1_LB2_MP0_MB_CP_WG

**Comment by RobsonRLemos** [comment]
@mkarunan thanks for the modifications to add the script to dump the benchmark output data to PTS. I have tested the rocWMMA datasets ingestion in the PTS system and everything is working fine. As soon as this PR #105 is approved we will work in the CI and PTS integration for the rocWMMA performance tests. Thanks.

**Review by cgmillette — APPROVED** [review]
LGTM

**Review by cgmillette — APPROVED** [review]
LGTM

**Pull request merged**
